server:
  port: 8080
  servlet:
    context-path: /v1
  tomcat:
    relaxed-query-chars: "{,},\\,|,^,[,],<,>"
    relaxed-path-chars: "{,},\\,|,^,[,],<,>"
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /v1/api-docs
  


environments:
  elastic:
    elasticPWD: "${ELASTIC_PASSWORD:14311982}"
    host: "${ES_HOST:localhost}"
    port: "${ES_PORT:9200}"
    protocol: "${ES_PROTOCOL:https}"



